on: [pull_request]
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node v12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
